export const STORAGE_KEYS = {
    MAIN_GOAL: 'mainGoal',
    MOTIVATION: 'motivation',
    MILESTONE_STACK: 'milestoneStack',
    ACTIVE_MILESTONE: 'activeMilestone',
    FOCUS_START_TIME: 'focusStartTime',
    FOCUS_TIMER_MODE: 'focusTimerMode',
    FOCUS_SESSION_HISTORY: 'focusSessionHistory',
    STREAK_DATA: 'streakData',
    DISTRACTION_LOG: 'distractionLog',
    USER_NAME: 'userName',
    AVATAR_COLOR: 'avatarColor',
    NOTIFICATIONS_ENABLED: 'notificationsEnabled',
    DAILY_REMINDER_TIME: 'dailyReminderTime',
    BACKUP_FREQUENCY: 'backupFrequency',
    LAST_BACKUP_DATE: 'lastBackupDate',
    BACKUP_DIRECTORY_URI: 'backupDirectoryUri',
};
